apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: htg7fei2t-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.fc33d7ee-72b3-4f39-b2c4-e8f26076fea8.prod.konfluxeaas.com/rhtap/rhtap-qe-nodejs:eaf415f409500d766ee80a6c399522518bf3ee14@sha256:b14ca89e07b8b0016f7558dbea6512354c7207486522426c231197a616d5e428
          name: container-image
