apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: htg7fei2t-nodejs
  janus-idp.io/tekton: htg7fei2t-nodejs
  backstage.io/kubernetes-id: htg7fei2t-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: htg7fei2t-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
