apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: htg7fei2t-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: htg7fei2t-nodejs 
  name: htg7fei2t-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: htg7fei2t-nodejs 
